# Generated by Django 5.1.15 on 2026-06-15 18:38

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0007_alter_qrscanevent_context'),
        ('inventory', '0007_alter_inventoryproduct_options_category_and_more'),
        ('makerspaces', '0012_makerspace_smtp_use_ssl'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventoryproduct',
            name='qty_sum_within_total',
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='needs_fix_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='inventoryproduct',
            constraint=models.CheckConstraint(condition=models.Q(('needs_fix_quantity__gte', 0)), name='qty_needs_fix_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='inventoryproduct',
            constraint=models.CheckConstraint(condition=models.Q(('total_quantity__gte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('available_quantity'), '+', models.F('reserved_quantity')), '+', models.F('issued_quantity')), '+', models.F('damaged_quantity')), '+', models.F('lost_quantity')), '+', models.F('needs_fix_quantity')))), name='qty_sum_within_total'),
        ),
    ]
