# Generated by Django 5.1.15 on 2026-06-19 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0009_qrscanevent_qrscan_ms_qrcode_created_idx_and_more'),
        ('makerspaces', '0018_alter_makerspace_frontend_domain'),
        ('operations', '0002_stocktakeledgerentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='qrprintbatch',
            index=models.Index(fields=['makerspace', '-created_at'], name='qrbatch_ms_created_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktakesession',
            index=models.Index(fields=['makerspace', 'status', '-started_at'], name='stktake_ms_status_start_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['makerspace', '-created_at'], name='stocktransfer_ms_created_idx'),
        ),
    ]
