# Generated by Django 5.1.15 on 2026-06-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_requests', '0011_hardwarerequestitemasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwarerequestitem',
            name='needs_fix_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
