# Generated by Django 5.1.15 on 2026-06-19 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0009_qrscanevent_qrscan_ms_qrcode_created_idx_and_more'),
        ('evidence', '0003_evidencephoto_purge_delete_guard'),
        ('hardware_requests', '0014_return_records_purge_delete_guard'),
        ('makerspaces', '0018_alter_makerspace_frontend_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hardwarerequest',
            index=models.Index(fields=['makerspace', 'status', '-created_at'], name='hwreq_ms_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='hardwarerequest',
            index=models.Index(fields=['makerspace', 'status', '-issued_at', '-created_at'], name='hwreq_ms_status_issued_idx'),
        ),
        migrations.AddIndex(
            model_name='hardwarerequest',
            index=models.Index(fields=['makerspace', 'status', '-updated_at', '-created_at'], name='hwreq_ms_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='hardwarerequest',
            index=models.Index(fields=['makerspace', 'status', '-closed_at'], name='hwreq_ms_status_closed_idx'),
        ),
    ]
