# Generated by Django 5.1.15 on 2026-06-19 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0008_immutable_purge_delete_guard'),
        ('hardware_requests', '0014_return_records_purge_delete_guard'),
        ('makerspaces', '0018_alter_makerspace_frontend_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='qrscanevent',
            index=models.Index(fields=['makerspace', 'qr_code', '-created_at'], name='qrscan_ms_qrcode_created_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscanevent',
            index=models.Index(fields=['makerspace', 'context'], name='qrscan_ms_context_idx'),
        ),
    ]
