# Generated by Django 5.1.15 on 2026-06-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0009_manualprintlog'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='manualprintlog',
            constraint=models.CheckConstraint(
                check=models.Q(grams_used__gt=0),
                name='manual_print_log_grams_positive',
            ),
        ),
    ]
