# Generated by Django 5.1.15 on 2026-06-19 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0011_printrequest_filament_grams_reserved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='printrequest',
            index=models.Index(fields=['requester', '-created_at'], name='printreq_requester_created_idx'),
        ),
        migrations.AddIndex(
            model_name='printrequest',
            index=models.Index(fields=['bucket', 'status', '-created_at'], name='printreq_bucket_status_idx'),
        ),
        migrations.AddIndex(
            model_name='printrequest',
            index=models.Index(fields=['bucket', 'payment_status', 'status'], name='printreq_bucket_payment_idx'),
        ),
    ]
