# Generated by Django 5.1.15 on 2026-06-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0012_printrequest_printreq_requester_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualprintlog',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
