# Generated by Django 5.1.15 on 2026-06-27 18:15

import django.core.validators
from django.db import migrations, models


def backfill_failed_at(apps, schema_editor):
    # Existing failed prints have no failed_at, so date-windowed report queries
    # would silently drop their partial hours. Seed failed_at from updated_at
    # (the closest available timestamp to when the row reached its failed state).
    PrintRequest = apps.get_model("printing", "PrintRequest")
    PrintRequest.objects.filter(status="failed", failed_at__isnull=True).update(
        failed_at=models.F("updated_at")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0016_manual_log_contact_and_request_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualprintlog',
            name='outcome',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=16),
        ),
        migrations.AddField(
            model_name='manualprintlog',
            name='percent_complete',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='manualprintlog',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='printrequest',
            name='fail_percent_complete',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='printrequest',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_failed_at, migrations.RunPython.noop),
    ]
