# Generated by Django 5.1.15 on 2026-06-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0011_enable_procurement_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerspace',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False),
        ),
    ]
