# Generated by Django 5.1.15 on 2026-06-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0020_makerspace_staff_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerspacemembership',
            name='receives_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
