# Generated by Django 5.1.15 on 2026-06-21 10:41

import apps.makerspaces.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0022_makerspace_public_stats_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerspace',
            name='map_url',
            field=models.URLField(blank=True, default='', validators=[apps.makerspaces.validators.validate_google_maps_url]),
        ),
    ]
