# Generated by Django 5.1.15 on 2026-06-22 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_emailnotificationmute'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailnotificationmute',
            new_name='integration_makersp_8c1f8c_idx',
            old_name='integration_makers_2fcfc9_idx',
        ),
    ]
