# Generated by Django 5.1.15 on 2026-06-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_emaillog_makerspace_status_created_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='integration_makersp_1d5eb0_idx',
            old_name='integration_emaill_makersp_8c9fd1_idx',
        ),
    ]
